
<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfmuscle/permission/users/add'));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'form-user-add');
$form->setAttribute('class', 'p-t-15');
$form->setAttribute('role', 'form');
$form->setAttribute('autocomplete', 'off');
?>

<?php // elseif ($element instanceof Zend\Form\Element\Captcha): ?>
    <!--<dd><?php // echo $this->formCaptcha($element) . $this->formElementErrors($element)                    ?></dd>-->
<?php // else: ?>
    <!--<dd><?php // echo $this->formInput($element) . $this->formElementErrors($element)                    ?></dd>-->
<?php // endif ?>

<div class="col-lg-12">
    <h1 class="page-header">New User</h1>
    <!-- START add Form -->
    <?php echo $this->form()->openTag($form) ?>
    <div class="panel panel-transparent ">

        <div class="panel-heading">
            <div class="panel-title pull-left">Edit User</div>
            <p class="pull-right">
<!--                <button class="btn btn-default btn-cons" type="button">White</button>
                <button class="btn btn-success btn-cons" type="button">Success</button>-->
                <?php echo $this->formButton($form->get('submit')) ?>
            </p>
        </div>
        <!-- Tab panes -->
        <div class="panel-body no-padding">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-transparent">
                        <ul class="nav nav-tabs nav-tabs-simple nav-tabs-left bg-white" id="tab-3">
                            <li class="active">
                                <a data-toggle="tab" href="#tabInformation">Information</a>
                            </li>
                            <li>
                                <a data-toggle="tab" href="#tabRole">Role</a>
                            </li>
                        </ul>

                        <div class="tab-content bg-white">
                            <div class="tab-pane active p-l-20 p-r-20" id="tabInformation">
                                <div class="row column-seperation">
                                    <div class="col-md-12">
                                        <h5 class="m-b-20">General Information</h5>
                                        <?php echo $this->formHidden($form->get('id')); ?>
                                        <div class="row clearfix">
                                            <div class="col-sm-6">
                                                <!-- START Form Control-->
                                                <div class="form-group form-group-default required">
                                                    <label><?php echo $form->get('firstname')->getLabel(); ?></label>
                                                    <?php echo $this->formInput($form->get('firstname')); ?>
                                                </div>
                                                <!-- END Form Control-->
                                            </div>
                                            <div class="col-sm-6">
                                                <!-- START Form Control-->
                                                <div class="form-group form-group-default required">
                                                    <label><?php echo $form->get('lastname')->getLabel(); ?></label>
                                                    <?php echo $this->formInput($form->get('lastname')); ?>
                                                </div>
                                                <!-- END Form Control-->
                                            </div>
                                        </div>

                                        <!-- START Form Control-->
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="form-group form-group-default required">
                                                    <label><?php echo $form->get('username')->getLabel(); ?></label>
                                                    <?php echo $this->formInput($form->get('username')); ?>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- END Form Control-->
                                        <!-- START Form Control-->
<!--                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="form-group form-group-default required">
                                                    <label><?php // echo $form->get('email')->getLabel(); ?></label>
                                                    <?php // echo $this->formInput($form->get('email')); ?>
                                                </div>
                                            </div>
                                        </div>-->
                                        <!-- END Form Control-->
<!--                                        <div class="row clearfix">
                                            <div class="col-sm-6">
                                                 START Form Control
                                                <div class="form-group form-group-default">
                                                    <label><?php // echo $form->get('password')->getLabel(); ?></label>
                                                    <?php // echo $this->formInput($form->get('password')); ?>
                                                </div>
                                                 END Form Control
                                            </div>
                                            <div class="col-sm-6">
                                                 START Form Control
                                                <div class="form-group form-group-default">
                                                    <label><?php // echo $form->get('passwordVerify')->getLabel(); ?></label>
                                                    <?php // echo $this->formInput($form->get('passwordVerify')); ?>
                                                </div>
                                                 END Form Control
                                            </div>
                                        </div>-->
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane p-l-20 p-r-20 p-t-20" id="tabRole">
                                <div class="row column-seperation">
                                    <div class="col-md-12">
                                        <h5 class="m-b-20">Assign User Role</h5>
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <div class="form-group form-group-default form-group-default-select2 required">
                                                    <label><?php echo $form->get('role')->getLabel(); ?></label>
                                                    <?php echo $this->formSelect($form->get('role')); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" id="redirect_on_success_url" name="redirect_on_success_url" value="<?php echo $this->url('zfmuscle/permission/users'); ?>" />
    <?php echo $this->form()->closeTag() ?>
    <!--END add Form-->
</div>