<?php

$rRoutes = [];
$rController = [];
//var_dump($this->roleResources); die;
foreach ($this->roleResources as $resourceObject)
{
    $rRoutes[] = $resourceObject->getResourceId();
    $rController[] = $resourceObject->getControllerId();
}
//var_dump($rValues); die;
?>
<!-- START Form Control-->
<div class="row">
    <div class="col-sm-6">
        <div class="form-group form-group-default form-group-default-select2 required">
            <label>Permission Scope</label>
            <select class="full-width" data-placeholder="Select Role Permission" data-init-plugin="select2" name="role_scope">
                <option value="all">All</option>
                <option value="custom">Custom</option>
            </select>
        </div>
    </div>
</div>
<!-- END Form Control-->

<ul id="role-resource">
<?php foreach ($this->resources as $key => $rArray): ?>
    <li>
        <div class="checkbox check-primary">
            <input type="checkbox" <?php echo (in_array($rArray['route'], $rRoutes)) ? 'checked = "checked"' : '' ?> name="resources[<?php echo $rArray['controller'];?>][]" value="<?php echo $rArray['route']; ?>" id="<?php echo $rArray['route']; ?>" />
            <label for="<?php echo $rArray['route']; ?>"><?php echo ucfirst($rArray['route']); ?></label>
        </div>
        <?php if (isset($rArray['child_routes']) && !empty($rArray['child_routes'])): ?>
            <ul>
                <?php foreach ($rArray['child_routes'] as $childRoute): ?>
                    <li>
                        <div class="checkbox check-primary">
                            <input type="checkbox" <?php echo (in_array($childRoute['route'], $rRoutes)) ? 'checked = "checked"' : '' ?> name="resources[<?php echo $childRoute['controller'];?>][]" value="<?php echo $childRoute['route']; ?>" id="<?php echo $childRoute['route']; ?>" />
                            <label for="<?php echo $childRoute['route']; ?>"><?php echo $childRoute['route']; ?></label>
                        </div>
<!--                        --><?php //if ($controller->getActions()): ?>
<!--                            <ul>-->
<!--                                --><?php //foreach ($controller->getActions() as $action): ?>
<!--                                    --><?php //$aTitle = $action->getTitle(); $aTitleId = strtolower($aTitle.$action->getId()); ?>
<!--                                    <li>-->
<!--                                        <div class="checkbox check-primary">-->
<!--                                            <input type="checkbox" --><?php //echo (in_array($action->getId(), $rActions)) ? 'checked = "checked"' : '' ?><!-- name="actions[]" value="--><?php //echo $action->getId(); ?><!--" id="--><?php //echo $aTitleId; ?><!--" />-->
<!--                                            <label for="--><?php //echo $aTitleId; ?><!--">--><?php //echo $aTitle; ?><!--</label>-->
<!--                                        </div>-->
<!--                                    </li>-->
<!--                                --><?php //endforeach; ?>
<!--                            </ul>-->
<!--                        --><?php //endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </li>
<?php endforeach ?>
</ul>