<div class="row">
    <div class="col-md-12">
        <!-- START PANEL -->
        <div class="panel">
            <div class="panel-heading">
                <!--<div class="panel-title">Roles</div>-->
                <?php $result = $this->RoleHelper()->isAllowed(array('zfmuscle-role'), 'entry'); ?>
                <?php if (isset($result['allow']) && $result['allow'] == true): ?>
                    <button class="btn btn-primary btn-xs pull-right m-b-10" onClick="window.location='<?php echo $this->url('zfmuscle/permission/roles/add') ?>';" title="Add new role">
                        <i class="glyphicon glyphicon-plus-sign"></i>&nbsp;&nbsp;Add new
                    </button>
                <?php endif; ?>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body" id="roleList">
                <?php echo $this->list; ?>
            </div>
        </div>
        <!-- END PANEL -->
    </div>
</div>