<!--<div style="float:left; padding-right:16px;"><?php // echo $this->gravatar($this->zfcUserIdentity()->getEmail())  ?></div>-->
<!--<h3><?php // echo $this->translate('Hello');  ?>, <?php // echo $this->zfcUserDisplayName()  ?>!</h3>-->
<!--<a href="<?php // echo $this->url('zfcuser/logout')  ?>">[<?php // echo $this->translate('Sign Out');  ?>]</a>-->
<!--<div style="clear:both;"></div>-->

<div class="dashboard">
    <div id="inner">
        <ul>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam delectus dolorum excepturi fugit,
                illum ipsam labore officia qui, reiciendis sapiente vel veritatis voluptatum? Accusantium dolor harum
                ipsa iste quasi velit!
            </li>
            <li>Atque, et facere. Accusamus, consequatur debitis dignissimos eaque in iure molestiae nesciunt quis
                suscipit? Blanditiis doloremque ipsam officia quam quo, sapiente tempore tenetur! Corporis ex illo
                obcaecati, quia quidem recusandae.
            </li>
            <li>Alias aperiam distinctio et facere fugit ipsum itaque iure laboriosam molestiae, numquam officiis
                recusandae sapiente? Amet deserunt dolore eligendi ex id ipsa, ipsum, laborum minima nisi, placeat
                possimus ut vel.
            </li>
        </ul>
    </div>
</div>