
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <?php foreach ($this->pages as $key => $page): ?>
        <?php if ($key < count($this->pages) - 1): ?>
            <li>
                <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
            </li>
        <?php else: ?>
            <li>
                <a class="active"><?php echo $page->getLabel(); ?></a>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<!-- END BREADCRUMB -->