
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
    <form role="search">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
        </div>
    </form>
    <ul class="nav menu">
        <?php $i = 1; foreach ($this->container as $index => $page): $moduleId = rand().time(); ?>
            <?php $result = array(); $routes = $page->get('route'); if ($routes) {
                if (strpos($routes, ',') !== FALSE) {
                    $routes = explode(',', $routes);
                    $result = $this->RoleHelper()->isAllowed($routes);
                } else {
                    $result = $this->RoleHelper()->isAllowed([$routes]);
                }
            } ?>

            <?php if (isset($result['allow']) && $result['allow'] == true): ?>
                <?php $spanId = $moduleId."".$index; ?>

                <?php if ($page->hasPages()): ?>
                    <li class="parent<?php echo " {$spanId} "; ?> ">
                        <a data-toggle="collapse" href="<?php echo "#sub-item-{$i}"; ?>">
                            <span class="glyphicon glyphicon-plus-sign" id="<?php echo $i; ?>"></span> <?php echo $page->getLabel(); ?> <?php $thumbnail = $page->get('thumbnail'); if ($thumbnail) { ?><span class="<?php echo "{$spanId} "; ?> glyphicon <?php echo " {$thumbnail} "; ?> menu-label"></span><?php } ?>
                        </a>
                        <ul class="children collapse" id="<?php echo "sub-item-{$i}"; ?>">
                            <?php foreach ($page->getPages() as $child): ?>
                                <?php $routes = $child->get('route') ? $child->get('route') : ''; ?>
                                <?php $result = $this->RoleHelper()->isAllowed([$routes]); ?>
                                <?php if (isset($result['allow']) && $result['allow'] == true): ?>
                                    <?php $subActive = ''; ?>
                                    <?php if ($child->isActive()): ?>
                                    <?php $subActive = 'active '; ?>
                                    <script type="application/javascript">
                                        var spanId = '<?php echo $spanId; ?>';
                                        jQuery('.'+spanId).addClass('active');
                                    </script>
                                    <?php endif; ?>
                                    <li class="<?php echo $subActive; ?>">
                                        <a class="" href="<?php echo (is_array($routes)) ? "#" : $child->getHref(); ?>">
                                            <?php echo $child->getLabel() ?> <?php $thumbnail = $child->get('thumbnail'); if ($thumbnail) { ?><span class="<?php echo $subActive; ?> glyphicon <?php echo " {$thumbnail} "; ?> sub-menu-label"></span><?php } ?>
                                        </a>
                                    </li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                <?php else: ?>
                    <li class="<?php echo $page->isActive() ? ' active' : ''; ?>">
                        <a href="<?php echo $page->getHref(); ?>">
                            <?php echo $page->getLabel() ?> <?php $thumbnail = $page->get('thumbnail'); if ($thumbnail) { ?><span class="glyphicon <?php echo " {$thumbnail} "; ?> menu-label<?php echo $page->isActive() ? ' active' : ''; ?>"></span><?php } ?>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endif; ?>
        <?php $i++; endforeach; ?>
    </ul>
</div><!--/.sidebar-->