<div class="row">
    <div class="col-md-12">
        <!-- START PANEL -->
        <div class="panel">
<!--            <div class="panel-heading">
                <div class="panel-title">Configuration</div>

                <button class="btn btn-primary btn-xs pull-right m-b-10" onClick="window.location = '<?php // echo $this->url('zfmuscle/permission/users/add') ?>';" title="Add new user">
                    <i class="glyphicon glyphicon-plus-sign"></i>&nbsp;&nbsp;Add new
                </button>
                <div class="clearfix"></div>
            </div>-->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover table-condensed" id="condensedTable">
                        <thead>
                            <tr>
                                <th style="width:80%">Configuration</th>
                                <th style="width:20%">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="v-align-middle semi-bold">System Role Resources</td>
                                <td class="v-align-middle semi-bold" nowrap="nowrap">
                                    <?php $result = $this->RoleHelper()->isAllowed(array('zfmuscle-system'), 'update-resource'); ?>
                                    <?php if (isset($result['allow']) && $result['allow'] == true): ?>
                                        <a class="btn btn-default btn-xs" href="<?php echo $this->url('zfmuscle/system/resource') ?>" title="Update">
                                            <i class="glyphicon glyphicon-forward"></i> Update
                                        </a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- END PANEL -->
    </div>
</div>