<?php echo $this->doctype(); ?>

<html lang="en" class="no-js">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZfMuscle | Manage your app the right way')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/zf-muscle/css/zf-muscle.css')
            ->prependStylesheet($this->basePath() . '/zf-muscle/css/bootstrap/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
            ->prependFile($this->basePath() . '/zf-muscle/js/dashboard.js')
            ->prependFile($this->basePath() . '/zf-muscle/js/jquery-validation/js/additional-methods.min.js')
            ->prependFile($this->basePath() . '/zf-muscle/js/jquery-validation/js/jquery.validate.min.js')
            ->prependFile($this->basePath() . '/zf-muscle/js/bootstrap/bootstrap.min.js')
            ->prependFile($this->basePath() . '/zf-muscle/js/jquery/jquery.min.js')
            ->prependFile($this->basePath() . '/zf-muscle/js/respond.min.js')
            ->prependFile($this->basePath() . '/zf-muscle/js/html5shiv.min.js')
        ;
        ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">
<!--                        <img width="20" height="20" alt="Brand" src="--><?php //echo $this->basePath() . '/zf-muscle/img/B.png'; ?><!--">-->
                        ZfMuscle
                    </a>
                    <?php if ($this->zfcUserIdentity()): ?>
                    <ul class="user-menu">
                        <li class="dropdown pull-right">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> User<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?php echo $this->url('zfmuscle/users/logout') ?>"><span class="glyphicon glyphicon-off"></span> Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                    <?php endif; ?>
                </div>

            </div><!-- /.container-fluid -->
        </nav>

        <?php
        $this->navigation('navigation')->menu()->setPartial('zf-muscle/partials/navigation');
        echo $this->navigation('navigation')->menu()->render();
        ?>

        <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
            <div class="row">
                <ol class="breadcrumb">
                    <li>
                        <a href="#"><span class="glyphicon glyphicon-home"></span></a>
                    </li>
                    <li class="active">Icons</li>
                </ol>
            </div><!--/.row-->

            <?php echo $this->content; ?>
        </div>

    </body>
</html>