<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZfMuscle | Manage your app the right way')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/zf-muscle/css/zf-muscle.css')
            ->prependStylesheet($this->basePath() . '/zf-muscle/css/reset.css')
            ->prependStylesheet($this->basePath() . '/zf-muscle/css/bootstrap/bootstrap.min.css')
        ?>

    </head>
    <body>

        <header class="cd-main-header">
            <a href="#0" class="cd-logo"><img src="<?php echo $this->basePath() . '/zf-muscle/img/cd-logo.svg'; ?>" alt="Logo"></a>
            <div class="cd-search is-hidden">
                <form action="#0">
                    <input type="search" placeholder="Search...">
                </form>
            </div> <!-- cd-search -->

            <a href="#0" class="cd-nav-trigger"><span></span></a>

            <nav class="cd-nav">
                <ul class="cd-top-nav">
                    <li><a href="#0">Tour</a></li>
                    <li><a href="#0">Support</a></li>

                    <?php if ($this->zfcUserIdentity()): ?>
                    <li class="has-children account">
                        <a href="#0">
                            <img src="<?php echo $this->basePath() . '/zf-muscle/img/cd-avatar.png'; ?>" alt="avatar">
                            Account
                        </a>
                        <ul>
                            <li><a href="#0">My Account</a></li>
                            <li><a href="#0">Edit Account</a></li>
                            <li><a href="<?php echo $this->url('zfmuscle/users/logout') ?>">Logout</a></li>
                        </ul>
                    </li>
                    <?php endif; ?>
                </ul>
            </nav>
        </header> <!-- .cd-main-header -->

        <main class="cd-main-content">
            <nav class="cd-side-nav">
                <?php
                $this->navigation('navigation')->menu()->setPartial('zf-muscle/partials/navigation');
                echo $this->navigation('navigation')->menu()->render();
                ?>
            </nav>

            <div class="content-wrapper">
                <!-- BREADCRUMBS -->
<!--                --><?php //echo $this->navigation('zfmuscle-navigation')->breadcrumbs()->setPartial('zf-muscle/partials/breadcrumbs'); ?>
                <!-- BREADCRUMBS ENDS -->

                <div class="no-display" style="display: none;">
                    <?php if (count($this->flashMessages)): ?>
                        <?php foreach ($this->flashMessages as $context => $messages): ?>
                            <div id="flash-type"><?php echo $context; ?></div>
                            <?php foreach ($messages as $message): ?>
                                <div id="flash-message"><?php echo $message; ?></div>;
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>

                <?php echo $this->content; ?>

                <hr>
                <footer>
                    <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>
            </div> <!-- .content-wrapper -->
        </main> <!-- .cd-main-content -->

    <!-- Scripts -->
    <?php
    echo $this->headScript()
        ->prependFile($this->basePath() . '/zf-muscle/js/dashboard.js')
        ->prependFile($this->basePath() . '/zf-muscle/js/jquery-menu/jquery.menu-aim.js')
        ->prependFile($this->basePath() . '/zf-muscle/js/jquery-form/jquery_form.js')
        ->prependFile($this->basePath() . '/zf-muscle/js/jquery-validation/js/additional-methods.min.js')
        ->prependFile($this->basePath() . '/zf-muscle/js/jquery-validation/js/jquery.validate.min.js')
        ->prependFile($this->basePath() . '/zf-muscle/js/bootstrap/bootstrap.min.js')
        ->prependFile($this->basePath() . '/zf-muscle/js/jquery/jquery-1.11.1.min.js')
    ;
    ?>

</body>
</html>