<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('DAS')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body style="padding-top: 70px;">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target=".navbar-collapse">
                        <span class="icon-bar"></span> <span class="icon-bar"></span> <span
                            class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('ZFMuscle') ?></a>
                </div>
                <div class="collapse navbar-collapse"><ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle profile-image" data-toggle="dropdown">  
                                    <?php // echo $this->zfcUserIdentity()->getDisplayName(); ?>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('zfcuser'); ?>"><i class="fa fa-cog"></i> Account</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->url('zfcuser/logout'); ?>"><i class="fa fa-sign-out"></i> Sign-out</a></li>
                                </ul>
                            </li>
                        </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php $breadcrumbs = $this->navigation()->breadcrumbs(); ?>
            <?php if (empty($breadcrumbs)): ?>
                <div class="breadcrumb"><?php echo $breadcrumbs; ?></div>
            <?php endif; ?>
            <?php
            if (count($this->flashMessages)) {
                foreach ($this->flashMessages as $context => $messages) {
                    echo '<div class="alert alert-' . $context . ' alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>';
                    foreach ($messages as $message) {
                        echo '<p>' . $message . '</p>';
                    }
                    echo '</div>';
                }
            }
            ?>

            <?php echo $this->content; ?>

            <hr>
            <footer>
                <p><strong>DAS</strong> &copy; <?php echo date('Y') ?> by Awoyo Oluwatoyin Stephen. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>