<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZfMuscle')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/zf-muscle/css/zf-muscle.css')
                ->prependStylesheet($this->basePath() . '/zf-muscle/css/reset.css')
                ->prependStylesheet($this->basePath() . '/zf-muscle/css/bootstrap/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/zf-muscle/js/login_install.js')
                ->prependFile($this->basePath() . '/zf-muscle/js/jquery-form/jquery_form.js')
                ->prependFile($this->basePath() . '/zf-muscle/js/jquery-validation/js/additional-methods.min.js')
                ->prependFile($this->basePath() . '/zf-muscle/js/jquery-validation/js/jquery.validate.min.js')
                ->prependFile($this->basePath() . '/zf-muscle/js/jquery/jquery-1.11.1.min.js')
        ;
        ?>

    </head>
    <body>
        <!-- START PAGE-CONTAINER -->
        <div class="container">
            <!-- END Login Background Pic Wrapper-->
            <!-- START Login Right Container-->
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                    <!-- main content -->
                    <?php echo $this->content; ?>

                    <hr>
                    <footer>
                        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
                    </footer>
                </div>
            </div>
            <!-- END Login Right Container-->
        </div>
        <!-- END PAGE CONTAINER -->
        
    </body>
</html>